on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to use for the PR validation'
        required: true
        type: string

    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    env:
      working-directory: './terraform'
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ${{ env.working-directory }}
        id: init
        run: terraform init

      - name: Terraform Workspace Select
        working-directory: ${{ env.working-directory }}
        id: workspace
        run: terraform workspace select ${{ inputs.environment }}

      - name: tfsec
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          working_directory: ${{ env.working-directory }}
          soft_fail: true

      - name: Terraform Apply
        working-directory: ${{ env.working-directory }}
        run: terraform apply -auto-approve
